### ISSUE TITLE
[FEATURE] allow for configuration of hot key

### ISSUE THREAD

**Issue by oolongtea** [Ecalzo/Skater#9]
This is minor, but a few people may have custom bindings that conflict with a default binding. Having a way to customize the binding would help those use another binding that doesn't conflict.

**Comment by Ecalzo** [comment]
Thanks for the suggestion 😄, hoping to enable this with https://github.com/Ecalzo/Skater/pull/10

**Comment by Ecalzo** [comment]
pushing the release up to the web store, may take ~1 week for approval
